#
# Copyright (C) 2024 ioyhp
#
name: Upload repo to release fox slow download

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set +e
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get install git
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Creating Package Artifact
        run: |
          git clone https://github.com/ioyhp/linux-4.9.269.git --single-branch --depth 1 -b main linux-4.9.269
          rm -rf ./linux-4.9.269/.git
          tar -cvf code.tar.xz ./linux-4.9.269/*
          echo "FINISH_TIME=$(date +%Y%m%d%-H%M%S)" >> $GITHUB_ENV
          
      - name: Delivering Package
        uses: actions/upload-artifact@v2
        with:
          name: code-linux-4.9.269-${{ env.FINISH_TIME }}
          path: ./code.tar.xz
  
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./code.tar.xz
          tag: code-${{ github.ref }}-${{ env.FINISH_TIME }}
          file_glob: true
          body: |
            ## Linux Amlogic 4.9.269 source
